Add workflow for incline service
TaskarCenterAtUW/TDEI-osw-datasvc-ts pull request #158
Opened 2024-09-19 09:27 UTC by sujata-m

2024-09-19 10:14 UTC, MashB requested changes

2024-09-19 10:14 UTC, MashB commented on src/controller/osw-controller.ts
> +        this.router.post(`${this.path}/dataset-add-inclination/`, authenticate, this.createInclineRequest);
rename dataset-add-inclination => dataset-inclination . POST suggests it is add.

2024-09-19 10:14 UTC, MashB commented on src/controller/osw-controller.ts
> +        this.router.post(`${this.path}/dataset-add-inclination/`, authenticate, this.createInclineRequest);
Remove trailing / from url

2024-09-19 10:14 UTC, MashB commented on src/controller/osw-controller.ts
> +                return next(new UnAuthenticated());
Return ForbiddenAccess() ,

2024-09-19 10:14 UTC, MashB commented on src/controller/osw-controller.ts
> +        this.router.post(`${this.path}/dataset-add-inclination/`, authenticate, this.createInclineRequest);
If dataset_id is mandatory and inclination is for dataset_id , then accept the input as part of path variable

2024-09-19 10:14 UTC, MashB commented on src/tdei-orchestrator-config_v2.json
> +                        "blobUrl": "<%=workflow_input.dataset_url%>",
should'nt be tasks.osw_dataset_incline_tag.output.file_upload_path ?

2024-09-19 10:21 UTC, MashB requested changes

2024-09-19 10:21 UTC, MashB commented on src/controller/osw-controller.ts
> +                    dataset_id: requestService.dataset_id
update only dataset id

2024-09-19 10:21 UTC, MashB commented on src/service/osw-service.ts
> +                    parameters: backendRequest.parameters
update dataset id only

2024-09-19 10:21 UTC, MashB commented on src/service/osw-service.ts
> +                parameters: backendRequest.parameters,
remove parameters its not used

2024-09-19 10:21 UTC, MashB commented on src/tdei-orchestrator-config_v2.json
> +                "parameters": "<%= JSON.stringify(parameters) %>",
parameters not used remove

2024-09-19 10:21 UTC, MashB commented on src/tdei-orchestrator-config_v2.json
> +                        "input_urls": "<%= JSON.stringify([decodeURIComponent(tasks.osw_incline_tag_osm_formatting.output.formatted_url), workflow_input.metadata_url, workflow_input.changeset_url]) %
changeset_url , metaurl missing in input please add

2024-09-23 10:15 UTC, susrisha requested changes
Spelling checks and also need to rebase

2024-09-23 10:15 UTC, susrisha commented on src/service/interface/osw-service-interface.ts
> +    calculateInclanation(backendRequest: InclinationServiceRequest): Promise<string>;
spell check. the method name should be `calculateInclination`

2024-09-23 10:15 UTC, susrisha commented on src/service/osw-service.ts
> +    async calculateInclanation(backendRequest: InclinationServiceRequest): Promise<string> {
please rename the method. there is spelling mistake

2024-09-25 16:34 UTC, merged